src/Entity/Peinture.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use App\Repository\PeintureRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PeintureRepository::class)
 * @ORM\Table(name="peintures")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class Peinture
{
    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    private $largeur;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    private $hauteur;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enVente;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateRealisation;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $portfolio;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @Vich\UploadableField(mapping="peinture_images", fileNameProperty="file")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="peintures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="peintures")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="peinture")
     */
    private $commentaires;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getFormatedPrice()
    {
        return number_format($this->getPrix(), 0, '', ' ') . ' F CFA';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLargeur(): ?string
    {
        return $this->largeur;
    }

    public function setLargeur(?string $largeur): self
    {
        $this->largeur = $largeur;

        return $this;
    }

    public function getHauteur(): ?string
    {
        return $this->hauteur;
    }

    public function setHauteur(?string $hauteur): self
    {
        $this->hauteur = $hauteur;

        return $this;
    }

    public function getEnVente(): ?bool
    {
        return $this->enVente;
    }

    public function setEnVente(?bool $enVente): self
    {
        $this->enVente = $enVente;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateRealisation(): ?\DateTimeInterface
    {
        return $this->dateRealisation;
    }

    public function setDateRealisation(?\DateTimeInterface $dateRealisation): self
    {
        $this->dateRealisation = $dateRealisation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPortfolio(): ?bool
    {
        return $this->portfolio;
    }

    public function setPortfolio(?bool $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setPeinture($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPeinture() === $this) {
                $commentaire->setPeinture(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Controller/PeinturesController.php
<?php

namespace App\Controller;

use App\Entity\Peinture;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use App\Service\CommentaireService;
use App\Repository\PeintureRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PeinturesController extends AbstractController
{
    /**
     * @Route("/realisations", name="app_peintures_realisation", methods={"GET"})
     */
    public function realisation(PeintureRepository $peintureRepo, PaginatorInterface $paginator, Request $request): Response
    {
        $data = $peintureRepo->findBy([], ['id' => 'DESC']);
        $peintures = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1), /*page number*/
            6 /*limit per page*/
        );

        return $this->render('peintures/realisation.html.twig', [
            'peintures' => $peintures,
            'current_menu' => 'realisations', 
        ]);
    }

    /**
     * @Route("/realisations/{slug}", name="app_peintures_show", methods={"GET", "POST"})
     */
    public function sow(Request $request, Peinture $peinture, CommentaireService $commentaireService, CommentaireRepository $commentaireRepo): Response
    {
        $commentaires = $commentaireRepo->findCommentaire($peinture);

        $commentaire = new Commentaire();

        $form = $this->createForm(CommentaireType::class, $commentaire);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $commentaire = $form->getData();
            $commentaireService->persistCommentaire($commentaire, null, $peinture);

            return $this->redirectToRoute('app_peintures_show', ['slug' => $peinture->getSlug()]);
        }
        return $this->render('peintures/show.html.twig', [
            'peinture' => $peinture,
            'current_menu' => 'realisations', 
            'form' => $form->createView(),
            'commentaires' => $commentaires,
        ]);
    }
}

templates/peintures/realisation.html.twig
{% extends "layouts/base.html.twig" %}

{% block title 'Ici se trouvent toutes nos réalisations'%}

{% block body %}
    <div class="container mt-5">
        <h1 class="fw-bold">Nos réalisations</h1>
        <p class="text-muted mb-4">Vous vous trouvez au meilleur endroit admirez!!!!</p>
        <div class="row">
            {% for peinture in peintures %}
                <div class="col-md-4 mb-3 d-flex align-items-stretch">
                    <div class="card peinture bg-white rounded shadow">
                        <div class="mw-100 overflow-hidden rounded-top">
                            <a class="text-decoration-none" href="{{ path('app_peintures_show', {slug: peinture.slug}) }}">
                                <img src="{{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('miniature') }}" class="card-img-top" alt="{{ peinture.nom }}">
                            </a>
                        </div>
                        <div class="card-body">
                            <a class="text-decoration-none text-muted" href="{{ path('app_peintures_show', {slug: peinture.slug}) }}">
                                <h5 class="card-title text-break">{{ peinture.nom }}</h5>
                                <p class="card-text text-break">{{ peinture.description | u.truncate(200, '...', false) }}</p>
                                <p class="card-text"><small class="text-muted">{{ peinture.createdAt | ago() }}</small></p>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            {% do peintures.setPageRange(2) %}
            {{ knp_pagination_render(peintures, 'layouts/pagination.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/peintures/show.html.twig
{% extends "layouts/base.html.twig" %}

{% block title peinture.nom %}

{% block body %}

    <div class="container-fluid px-md-0 mt-3">
        <div class="row justify-content-between gx-0 mx-md-0 mb-6 mb-md-2">
            <div class="col-12 col-md-3 vh-md-100 mx-auto" style="top: 0;">
                <aside class="flex-grow-1 py-8 py-md-10">
                    <div>
                        <h2>{{ peinture.nom }}</h2>
                        {% for categorie in peinture.categorie %}
                            <span class="badge bg-secondary">{{ categorie.nom }}</span>    
                        {% endfor %}
                    </div>
                    <p class="fs-lg mb-7 text-muted text-break mt-2">
                        {{ peinture.description | nl2br}}
                    </p>
                    <dv>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <h6 class="d-flex mb-0 text-uppercase">
                                Date de réalisation
                                <span class="ms-auto">{{ peinture.dateRealisation | date('d/m/Y')}}</span>
                            </h6>
                        </li>
                        <li class="list-group-item">
                            <h6 class="d-flex mb-0 text-uppercase">
                                Largeur
                                <span class="ms-auto">{{ peinture.largeur }} cm</span>
                            </h6>
                        </li>
                        <li class="list-group-item">
                            <h6 class="d-flex mb-0 text-uppercase">
                                Hauteur
                                <span class="ms-auto">{{ peinture.hauteur }} cm</span>
                            </h6>
                        </li>
                        {% if peinture.enVente %}
                            <li class="list-group-item">
                                <h6 class="d-flex mb-0 text-uppercase">
                                    <strong>Disponible à la vente</strong>
                                    <span class="ms-auto"><strong>{{ peinture.formatedPrice }}</strong></span>
                                </h6>
                            </li>
                        {% endif %}
                    </ul>
                </aside>
            </div>
            <div class="col-12 col-md-8 mb-5">
                <div class="pt-md-10">
                    <img class="w-100 h-auto" src="{{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('full') }}" alt="">
                </div>
            </div>
        </div>
    </div>

    {{ include('commentaire/form.html.twig') }}
    {{ include('commentaire/commentaires.html.twig') }}
    
{% endblock %}